<?php

/**
 * @file
 * Provides some common configurable blocks for use in the Spacelift theme
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function aluminum_blocks_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.aluminum_blocks':
      return check_markup(file_get_contents(dirname(__FILE__) . "/README.txt"));
  }
}

function aluminum_blocks_theme($existing, $type, $theme, $path) {
  return [
    'aluminum_follow_list' => [
      'variables' => ['list' => NULL, 'link_target' => NULL],
    ],
    'aluminum_link_list' => [
      'variables' => ['list' => NULL],
    ],
    'aluminum_dropdown_links' => [
      'variables' => ['link_list' => NULL, 'button_text' => NULL],
    ],
    'aluminum_phone_number' => [
      'variables' => ['phone_number' => NULL, 'url' => NULL]
    ],
    'aluminum_phone_number_list' => [
      'variables' => ['list' => NULL],
    ],
    'aluminum_content' => [
      'variables' => ['entity_Type' => NULL, 'entity_id' => NULL, 'view_mode' => NULL]
    ],
    'aluminum_office_info' => [
      'variables' => ['address' => NULL, 'phone_list' => NULL, 'office_hours' => NULL]
    ],
    'aluminum_icon' => [
      'variables' => ['icon' => NULL, 'output_as_link' => NULL, 'link_url' => NULL]
    ],
    'aluminum_link' => [
      'variables' => ['title' => NULL, 'url' => NULL, 'classes' => []],
    ],
    'aluminum_script_tag' => [
      'variables' => ['wrapper_classes' => '', 'wrapper_id' => '', 'script' => NULL],
    ],
    'aluminum_iframe' => [
      'variables' => [
        'src' => NULL,
        'width' => NULL,
        'height' => NULL,
        'remove_border' => NULL,
        'responsive' => NULL,
        'fit_content' => NULL,
        'name' => NULL,
      ],
    ],
  ];
}
